export const AppRoutes = {
  root: "/",
  about: "about",
  contact: "contact",
  termAndConditions: "term-and-conditions",
  auth: "auth/*",
  admin: "admin/*",
  users: "users/*",
  products: "categories/*",
  cart: "cart/*",
  checkout: "checkout/*",
  settings: "settings",
  profile: "profile",
  changePassword: "change-password",
  all: "*",
};
